# ****************************************************************************
# NOTES:
#
# Workflow for updating data in data repository.
#
#
# ****************************************************************************

name: Data update test

on:
  push:
    branches:
      - develop
    
# on:
#   push:
#     branches:
#       - develop

jobs:
  data-update:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with: 
        r-version: 4.1.3
  
    - name: Cache R packages
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-dataupdate
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        install.packages(c("dplyr", "RSQLite", "readr", "cansim", "stringr", "lubridate", "tidyr"))
      shell: Rscript {0}

    - name: Updating data and cleaning 
      run: |
        source('automation_script.R')
      shell: Rscript {0}
  
    # - name: Check if there are any changes
    #   id: verify_diff
    #   run: |
    #     git diff --quiet . || echo "::set-output name=new_data_exists::true"

    - name: Commit files
      # if: steps.verify_diff.outputs.new_data_exists == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Add new data updates"

    - name: Push changes
      # if: steps.verify_diff.outputs.new_data_exists == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
